import Sidebar from '@/components/Sidebar'


export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <div className='flex w-full h-full'>

        <Sidebar/>
        <main className='ml-20 w-full h-full'>
        {children}
        </main>
        
        
        
        </div>
  )
}
