import './globals.css'
import { AppWrapper } from '@/app/admin/settings/page';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <AppWrapper>
      {/* Ваш код приложения */}
    
      <body className='h-screen w-screen '>
        {children}
        </body>
        </AppWrapper>
    </html>
  )
}
